### ISSUE TITLE
デプロイについての質問です

### ISSUE THREAD

**Issue by CHRISPINE3** [tomomano/learn-aws-by-coding-source-code#4]
58Pのデプロイを実行したのですが、出力の中に「InstancePublicIp」を確認できませんでした。

![無題](https://user-images.githubusercontent.com/96678548/147406452-21d68cee-3d2f-4395-b6d9-9ce65eac6e1b.png)
このような場合、どのようなことが原因かご教示いただけますでしょうか。

**Comment by CHRISPINE3** [comment]
@tomomano

お忙しい中返信していただき、ありがとうございます。

"Do you wish to deploy these changes (y/n)?"　こちらについては確認できませんでした。
しかしcmdで行っていたところをubuntuで再度試したところ成功しました。

本書に記載があったにも関わらず、私の確認不足でご迷惑をおかけして申し訳ありません。

**Comment by tomomano** [comment]
@CHRISPINE3 

無事成功したということでよかったです👍
またなにかあったら issues までお願いします．
